export const surpriseMePrompts = [
    "a Renaissance-style oil painting of a lone cowboy on horseback in the desert",
    "a futuristic 3D rendering of a robotic horse ridden by a cowboy",
    "an ultra-realistic photograph of a horse grazing in a field, shot with a film camera",
    "a surrealist dream-like painting of a cowboy riding a giant rabbit through a desert landscape",
    "a digital art piece of a cowboy sitting on a cactus, with a sunset in the background",
    "a black and white photograph of a cowboy and his horse, taken with a vintage camera",
    "an oil painting of a cowboy hat and boots sitting on a wooden fence post",
    "a sculpture of a cowboy riding a bucking bronco made entirely out of recycled materials",
    "a colorful watercolor painting of a group of cowboys herding cattle through a river",
    "a digital art piece of a cowboy standing in front of a neon sign in a futuristic city",
    "an ultra-realistic portrait of a cowboy's weathered face, with wrinkles and stubble visible",
    "a surrealist dream-like painting of a horse with butterfly wings, being ridden by a cowboy",
    "a futuristic 3D rendering of a cowboy riding a hoverbike across a barren landscape",
    "a charcoal drawing of a cowboy silhouetted against a desert sunset",
    "an oil painting of a cowboy cooking beans over a campfire in the wilderness",
    "a digital art piece of a cowboy riding a mechanical bull in a neon-lit saloon",
    "an ultra-realistic photograph of a cowboy's spurs and leather chaps, shot with a macro lens",
    "a surrealist dream-like painting of a cowboy riding a giant armadillo through a ghost town",
    "a watercolor painting of a group of cowboys playing cards in a dusty saloon",
    "a futuristic 3D rendering of a cowboy on a jetpack, soaring through a canyon",
    "a Baroque-style oil painting of a group of cowboys engaged in a shoot-out",
    "a surrealist dream-like painting of a cowboy riding a giant scorpion through a desert landscape, with a blood red sky in the background",
    "a hyper-realistic photograph of a cowboy and his horse, shot with a large format film camera",
    "a mixed media piece of a cowboy hat made out of feathers, leather, and beads",
    "an impressionist-style painting of a herd of wild horses galloping across a prairie",
    "a digital art piece of a cowboy riding a mechanical bull in a neon-lit rodeo arena, with a crowd of cheering spectators in the background",
    "a sculpture of a cowboy made out of scrap metal and discarded machine parts, with gears and wires visible",
    "an oil painting of a cowboy on horseback, with a stormy sky and lightning bolts in the background",
    "a surrealistic painting of a cowboy with a long neck like a giraffe, riding a horse with a snake for a tail",
    "a futuristic 3D rendering of a cowboy riding a hoverhorse across a neon cityscape",
    "a charcoal drawing of a cowboy's weathered boots, with intricate patterns etched into the leather",
    "a digital art piece of a cowboy riding a motorcycle through a desert canyon, with a fiery sunset in the background",
    "an abstract painting of a cowboy's silhouette against a bright, colorful background",
    "a photograph of a cowboy's lasso suspended in mid-air, shot with a high-speed camera",
    "a surrealist dream-like painting of a cowboy riding a giant rattlesnake through a dark, eerie forest",
    "an oil painting of a cowboy and his horse reflected in the still waters of a mountain lake",
    "a digital art piece of a cowboy sitting on a throne made out of cactus needles and scorpion tails, with a starry sky in the background",
    "a hyper-realistic painting of a group of cowboys playing poker in a smoky saloon, with cards and chips rendered in painstaking detail",
    "a sculpture of a horse made entirely out of driftwood, with intricate textures and patterns visible",
    "a futuristic 3D rendering of a cowboy on a hoverboard, racing through a twisting canyon with sheer cliffs on either side",
    "a realistic portrait photograph of an aged cowboy, with a rugged face and piercing blue eyes",
    "a black and white 35mm photograph of a lone cowboy on horseback, silhouetted against a vast, open sky",
    "a close-up 35mm photograph of a cowboy's weathered hands, with the intricate details of the leather and stitching visible",
    "a portrait photograph of a Native American warrior, with striking features and traditional dress",
    "a 35mm photograph of a cowboy sitting outside a saloon, with a pistol in his lap and a look of steely determination on his face",
    "a photograph of a group of cowboys and their horses, taken at dusk with the warm, golden light of the setting sun",
    "a portrait photograph of a female sharpshooter, with a confident smile and a revolver at her side",
    "a candid 35mm photograph of a cowboy taking a break from work, smoking a cigarette and looking off into the distance",
    "a photograph of a group of Native American dancers performing a traditional dance, with vibrant costumes and intricate movements",
    "a close-up 35mm photograph of a cowboy's spurs, with the intricate details of the metalwork visible and the leather straps worn and frayed",
];
